/-
Generated by the port script. Run with `lake env lean scripts/AxiomCheck.lean`.
For every ported top-level statement (each former concept-package axiom, now a theorem)
this prints `#print axioms` and fails unless the axioms used are among
`propext`, `Classical.choice` and `Quot.sound`.
-/
import Complexity
import Complexity.StatementCheck

open Lean Elab Command in
elab "#check_standard_axioms " ids:ident* : command => do
  let allowed : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let mut bad : Array (Name × Array Name) := #[]
  for id in ids do
    let n ← liftCoreM <| realizeGlobalConstNoOverloadWithInfo id
    let axs ← collectAxioms n
    let extra := axs.filter fun a => !allowed.contains a
    logInfo m!"{n} depends on axioms: {axs.toList}"
    if !extra.isEmpty then bad := bad.push (n, extra)
  if !bad.isEmpty then
    throwError "non-standard axioms found: {bad.toList}"
  logInfo m!"{ids.size} statements checked: only propext, Classical.choice, Quot.sound are used."

#print axioms Complexity.ArcKayles.Biclique.value_eq
#print axioms Complexity.ArcKayles.Completeness.membership
#print axioms Complexity.ArcKayles.Completeness.pspace_complete
#print axioms Complexity.ArcKayles.GrundyProperties.disjoint_union
#print axioms Complexity.ArcKayles.GrundyProperties.losing_iff_zero
#print axioms Complexity.ArcKayles.GrundyProperties.smaller_reachable
#print axioms Complexity.ArcKayles.GrundyProperties.value_not_reachable
#print axioms Complexity.ArcKayles.Passes.outcome_equivalent
#print axioms Complexity.ArcKayles.PositiveCNFHardness.hard
#print axioms Complexity.ArcKayles.Reduction.false_strategy
#print axioms Complexity.ArcKayles.Reduction.polynomial_reduction
#print axioms Complexity.ArcKayles.Reduction.true_strategy
#print axioms Complexity.ArcKayles.RegularPlay.deviation_loses
#print axioms Complexity.ArcKayles.RegularPlay.exceptional_parity
#print axioms Complexity.ArcKayles.Sizes.construction_size
#print axioms Complexity.ArcKayles.Sizes.formula_length
#print axioms Complexity.ArcKayles.Sizes.graph_length
#print axioms Complexity.Classical.BasicProperties.L_subset_NL
#print axioms Complexity.Classical.BasicProperties.NL_subset_P
#print axioms Complexity.Classical.BasicProperties.NPSPACE_subset_EXPTIME
#print axioms Complexity.Classical.BasicProperties.NP_subset_PSPACE
#print axioms Complexity.Classical.BasicProperties.P_subset_NP
#print axioms Complexity.Classical.Certificates.pair_injective
#print axioms Complexity.Classical.Certificates.pair_length
#print axioms Complexity.Classical.Certificates.unpair_pair
#print axioms Complexity.Classical.ComplementClosure.closed_under_complement
#print axioms Complexity.Classical.FiniteStackEquivalence.finiteStackP_eq_P
#print axioms Complexity.Classical.ModelEquivalence.singleTapeP_eq_P
#print axioms Complexity.Classical.PolynomialSpaceEquality.PSPACE_eq_NPSPACE
#print axioms Complexity.Classical.SingleTapeComplement.closed_under_complement
#print axioms Complexity.CookLevin.CircuitMachine.compile
#print axioms Complexity.CookLevin.CookLevin.np_complete
#print axioms Complexity.CookLevin.EncodingCorrect.roundtrip
#print axioms Complexity.CookLevin.FiniteWitness.bounded
#print axioms Complexity.CookLevin.GateCorrect.correct
#print axioms Complexity.CookLevin.SATEncoding.correct
#print axioms Complexity.CookLevin.SATHard.hardness
#print axioms Complexity.CookLevin.SATinNP.membership
#print axioms Complexity.CookLevin.TseitinCorrect.correct
#print axioms Complexity.CookLevin.VerifierCorrect.correct
#print axioms Complexity.CookLevin.VerifierTime.polynomial

#check_standard_axioms
  Complexity.ArcKayles.Biclique.value_eq
  Complexity.ArcKayles.Completeness.membership
  Complexity.ArcKayles.Completeness.pspace_complete
  Complexity.ArcKayles.GrundyProperties.disjoint_union
  Complexity.ArcKayles.GrundyProperties.losing_iff_zero
  Complexity.ArcKayles.GrundyProperties.smaller_reachable
  Complexity.ArcKayles.GrundyProperties.value_not_reachable
  Complexity.ArcKayles.Passes.outcome_equivalent
  Complexity.ArcKayles.PositiveCNFHardness.hard
  Complexity.ArcKayles.Reduction.false_strategy
  Complexity.ArcKayles.Reduction.polynomial_reduction
  Complexity.ArcKayles.Reduction.true_strategy
  Complexity.ArcKayles.RegularPlay.deviation_loses
  Complexity.ArcKayles.RegularPlay.exceptional_parity
  Complexity.ArcKayles.Sizes.construction_size
  Complexity.ArcKayles.Sizes.formula_length
  Complexity.ArcKayles.Sizes.graph_length
  Complexity.Classical.BasicProperties.L_subset_NL
  Complexity.Classical.BasicProperties.NL_subset_P
  Complexity.Classical.BasicProperties.NPSPACE_subset_EXPTIME
  Complexity.Classical.BasicProperties.NP_subset_PSPACE
  Complexity.Classical.BasicProperties.P_subset_NP
  Complexity.Classical.Certificates.pair_injective
  Complexity.Classical.Certificates.pair_length
  Complexity.Classical.Certificates.unpair_pair
  Complexity.Classical.ComplementClosure.closed_under_complement
  Complexity.Classical.FiniteStackEquivalence.finiteStackP_eq_P
  Complexity.Classical.ModelEquivalence.singleTapeP_eq_P
  Complexity.Classical.PolynomialSpaceEquality.PSPACE_eq_NPSPACE
  Complexity.Classical.SingleTapeComplement.closed_under_complement
  Complexity.CookLevin.CircuitMachine.compile
  Complexity.CookLevin.CookLevin.np_complete
  Complexity.CookLevin.EncodingCorrect.roundtrip
  Complexity.CookLevin.FiniteWitness.bounded
  Complexity.CookLevin.GateCorrect.correct
  Complexity.CookLevin.SATEncoding.correct
  Complexity.CookLevin.SATHard.hardness
  Complexity.CookLevin.SATinNP.membership
  Complexity.CookLevin.TseitinCorrect.correct
  Complexity.CookLevin.VerifierCorrect.correct
  Complexity.CookLevin.VerifierTime.polynomial
