/-
Generated by the port script. Run with `lake env lean scripts/AxiomCheck.lean`.
For every ported top-level statement (each former concept-package axiom, now a theorem)
and every milestone-2 and milestone-3 theorem, this prints `#print axioms` and fails unless the axioms used are among
`propext`, `Classical.choice` and `Quot.sound`.
-/
import Complexity
import Complexity.StatementCheck
import ReticuliProver.SHA256

open Lean Elab Command in
elab "#check_standard_axioms " ids:ident* : command => do
  let allowed : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let mut bad : Array (Name × Array Name) := #[]
  for id in ids do
    let n ← resolveGlobalConstNoOverload id
    let axs ← collectAxioms n
    let extra := axs.filter fun a => !allowed.contains a
    logInfo m!"{n} depends on axioms: {axs.toList}"
    if !extra.isEmpty then bad := bad.push (n, extra)
  if !bad.isEmpty then
    throwError "non-standard axioms found: {bad.toList}"
  logInfo m!"{ids.size} statements checked: only propext, Classical.choice, Quot.sound are used."

#print axioms Complexity.ArcKayles.Biclique.value_eq
#print axioms Complexity.ArcKayles.Completeness.membership
#print axioms Complexity.ArcKayles.Completeness.pspace_complete
#print axioms Complexity.ArcKayles.GrundyProperties.disjoint_union
#print axioms Complexity.ArcKayles.GrundyProperties.losing_iff_zero
#print axioms Complexity.ArcKayles.GrundyProperties.smaller_reachable
#print axioms Complexity.ArcKayles.GrundyProperties.value_not_reachable
#print axioms Complexity.ArcKayles.Passes.outcome_equivalent
#print axioms Complexity.ArcKayles.PositiveCNFHardness.hard
#print axioms Complexity.ArcKayles.Reduction.false_strategy
#print axioms Complexity.ArcKayles.Reduction.polynomial_reduction
#print axioms Complexity.ArcKayles.Reduction.true_strategy
#print axioms Complexity.ArcKayles.RegularPlay.deviation_loses
#print axioms Complexity.ArcKayles.RegularPlay.exceptional_parity
#print axioms Complexity.ArcKayles.Sizes.construction_size
#print axioms Complexity.ArcKayles.Sizes.formula_length
#print axioms Complexity.ArcKayles.Sizes.graph_length
#print axioms Complexity.Classes.BasicProperties.L_subset_NL
#print axioms Complexity.Classes.BasicProperties.NL_subset_P
#print axioms Complexity.Classes.BasicProperties.NPSPACE_subset_EXPTIME
#print axioms Complexity.Classes.BasicProperties.NP_subset_PSPACE
#print axioms Complexity.Classes.BasicProperties.P_subset_NP
#print axioms Complexity.Classes.Certificates.pair_injective
#print axioms Complexity.Classes.Certificates.pair_length
#print axioms Complexity.Classes.Certificates.unpair_pair
#print axioms Complexity.Classes.ComplementClosure.closed_under_complement
#print axioms Complexity.Classes.FiniteStackEquivalence.finiteStackP_eq_P
#print axioms Complexity.Classes.ModelEquivalence.singleTapeP_eq_P
#print axioms Complexity.Classes.PolynomialSpaceEquality.PSPACE_eq_NPSPACE
#print axioms Complexity.Classes.SingleTapeComplement.closed_under_complement
#print axioms Complexity.CookLevin.CircuitMachine.compile
#print axioms Complexity.CookLevin.CookLevin.np_complete
#print axioms Complexity.CookLevin.EncodingCorrect.roundtrip
#print axioms Complexity.CookLevin.FiniteWitness.bounded
#print axioms Complexity.CookLevin.GateCorrect.correct
#print axioms Complexity.CookLevin.SATEncoding.correct
#print axioms Complexity.CookLevin.SATHard.hardness
#print axioms Complexity.CookLevin.SATinNP.membership
#print axioms Complexity.CookLevin.TseitinCorrect.correct
#print axioms Complexity.CookLevin.VerifierCorrect.correct
#print axioms Complexity.CookLevin.VerifierTime.polynomial

-- Milestone 2 statements
#print axioms Complexity.Savitch.NPSPACE_subset_PSPACE
#print axioms Complexity.Savitch.PSPACE_subset_NPSPACE
#print axioms Complexity.Savitch.PSPACE_eq_NPSPACE
#print axioms Complexity.Games.Game.language_mem_PSPACE
#print axioms Complexity.Games.Game.winning_iff
#print axioms Complexity.QBF.decode_encode
#print axioms Complexity.QBF.decode_closed
#print axioms Complexity.QBF.TQBFGame.language_eq
#print axioms Complexity.QBF.Reduction.translate_true
#print axioms Complexity.QBF.ReductionCode.reduction_polynomial
#print axioms Complexity.QBF.TQBF_mem_PSPACE
#print axioms Complexity.QBF.TQBF_hard
#print axioms Complexity.QBF.TQBF_complete

-- Milestone 3 statements
#print axioms Complexity.Modular.j_mul_discriminant
#print axioms Complexity.Modular.j_mul_E₄_cube_sub_E₆_sq
#print axioms Complexity.Modular.j_eq_E₄_cube_sub_E₆_sq
#print axioms Complexity.Modular.j_SL_smul
#print axioms Complexity.Modular.j_slash_invariant
#print axioms Complexity.Modular.discriminant_coeff_two
#print axioms Complexity.Modular.discriminant_coeff_three
#print axioms Complexity.Modular.cuspFunction_qj_eqOn
#print axioms Complexity.Modular.cuspFunction_qj_zero
#print axioms Complexity.Modular.differentiableOn_cuspFunction_qj
#print axioms Complexity.Modular.hasSum_qExpansion_qj
#print axioms Complexity.Modular.j_eq_tsum
#print axioms Complexity.Modular.qExpansion_qj_coeff_zero
#print axioms Complexity.Modular.qExpansion_qj_coeff_one
#print axioms Complexity.Modular.qExpansion_qj_coeff_two
#print axioms Complexity.Modular.j_expansion

-- SHA-256 ground: test vectors and the genesis sanity check
#print axioms ReticuliProver.SHA256.sha256_empty
#print axioms ReticuliProver.SHA256.sha256_abc
#print axioms ReticuliProver.SHA256.sha256_two_block
#print axioms ReticuliProver.Mining.genesis_doubleSHA256
#print axioms ReticuliProver.Mining.genesis_target
#print axioms ReticuliProver.Mining.genesis_meetsTarget
#print axioms ReticuliProver.Mining.genesis_validCompact

#check_standard_axioms
  Complexity.ArcKayles.Biclique.value_eq
  Complexity.ArcKayles.Completeness.membership
  Complexity.ArcKayles.Completeness.pspace_complete
  Complexity.ArcKayles.GrundyProperties.disjoint_union
  Complexity.ArcKayles.GrundyProperties.losing_iff_zero
  Complexity.ArcKayles.GrundyProperties.smaller_reachable
  Complexity.ArcKayles.GrundyProperties.value_not_reachable
  Complexity.ArcKayles.Passes.outcome_equivalent
  Complexity.ArcKayles.PositiveCNFHardness.hard
  Complexity.ArcKayles.Reduction.false_strategy
  Complexity.ArcKayles.Reduction.polynomial_reduction
  Complexity.ArcKayles.Reduction.true_strategy
  Complexity.ArcKayles.RegularPlay.deviation_loses
  Complexity.ArcKayles.RegularPlay.exceptional_parity
  Complexity.ArcKayles.Sizes.construction_size
  Complexity.ArcKayles.Sizes.formula_length
  Complexity.ArcKayles.Sizes.graph_length
  Complexity.Classes.BasicProperties.L_subset_NL
  Complexity.Classes.BasicProperties.NL_subset_P
  Complexity.Classes.BasicProperties.NPSPACE_subset_EXPTIME
  Complexity.Classes.BasicProperties.NP_subset_PSPACE
  Complexity.Classes.BasicProperties.P_subset_NP
  Complexity.Classes.Certificates.pair_injective
  Complexity.Classes.Certificates.pair_length
  Complexity.Classes.Certificates.unpair_pair
  Complexity.Classes.ComplementClosure.closed_under_complement
  Complexity.Classes.FiniteStackEquivalence.finiteStackP_eq_P
  Complexity.Classes.ModelEquivalence.singleTapeP_eq_P
  Complexity.Classes.PolynomialSpaceEquality.PSPACE_eq_NPSPACE
  Complexity.Classes.SingleTapeComplement.closed_under_complement
  Complexity.CookLevin.CircuitMachine.compile
  Complexity.CookLevin.CookLevin.np_complete
  Complexity.CookLevin.EncodingCorrect.roundtrip
  Complexity.CookLevin.FiniteWitness.bounded
  Complexity.CookLevin.GateCorrect.correct
  Complexity.CookLevin.SATEncoding.correct
  Complexity.CookLevin.SATHard.hardness
  Complexity.CookLevin.SATinNP.membership
  Complexity.CookLevin.TseitinCorrect.correct
  Complexity.CookLevin.VerifierCorrect.correct
  Complexity.CookLevin.VerifierTime.polynomial
  Complexity.Savitch.NPSPACE_subset_PSPACE
  Complexity.Savitch.PSPACE_subset_NPSPACE
  Complexity.Savitch.PSPACE_eq_NPSPACE
  Complexity.Games.Game.language_mem_PSPACE
  Complexity.Games.Game.winning_iff
  Complexity.QBF.decode_encode
  Complexity.QBF.decode_closed
  Complexity.QBF.TQBFGame.language_eq
  Complexity.QBF.Reduction.translate_true
  Complexity.QBF.ReductionCode.reduction_polynomial
  Complexity.QBF.TQBF_mem_PSPACE
  Complexity.QBF.TQBF_hard
  Complexity.QBF.TQBF_complete
  Complexity.Modular.j_mul_discriminant
  Complexity.Modular.j_mul_E₄_cube_sub_E₆_sq
  Complexity.Modular.j_eq_E₄_cube_sub_E₆_sq
  Complexity.Modular.j_SL_smul
  Complexity.Modular.j_slash_invariant
  Complexity.Modular.discriminant_coeff_two
  Complexity.Modular.discriminant_coeff_three
  Complexity.Modular.cuspFunction_qj_eqOn
  Complexity.Modular.cuspFunction_qj_zero
  Complexity.Modular.differentiableOn_cuspFunction_qj
  Complexity.Modular.hasSum_qExpansion_qj
  Complexity.Modular.j_eq_tsum
  Complexity.Modular.qExpansion_qj_coeff_zero
  Complexity.Modular.qExpansion_qj_coeff_one
  Complexity.Modular.qExpansion_qj_coeff_two
  Complexity.Modular.j_expansion
  ReticuliProver.SHA256.sha256_empty
  ReticuliProver.SHA256.sha256_abc
  ReticuliProver.SHA256.sha256_two_block
  ReticuliProver.Mining.genesis_doubleSHA256
  ReticuliProver.Mining.genesis_target
  ReticuliProver.Mining.genesis_meetsTarget
  ReticuliProver.Mining.genesis_validCompact
