/-
Generated by the port script: every removed concept axiom is restated verbatim
here (binders and statement copied from the archived concept file) and checked against
the theorem that now carries its name. If a ported proof ever proved a different
statement than the archived concept, this file fails to build.
-/
import Complexity

namespace Complexity.Classical.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : L ⊆ NL :=
  @Complexity.Classical.BasicProperties.L_subset_NL
end Complexity.Classical.BasicProperties

namespace Complexity.Classical.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : NL ⊆ P :=
  @Complexity.Classical.BasicProperties.NL_subset_P
end Complexity.Classical.BasicProperties

namespace Complexity.Classical.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : P ⊆ NP :=
  @Complexity.Classical.BasicProperties.P_subset_NP
end Complexity.Classical.BasicProperties

namespace Complexity.Classical.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : NP ⊆ PSPACE :=
  @Complexity.Classical.BasicProperties.NP_subset_PSPACE
end Complexity.Classical.BasicProperties

namespace Complexity.Classical.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : NPSPACE ⊆ EXPTIME :=
  @Complexity.Classical.BasicProperties.NPSPACE_subset_EXPTIME
end Complexity.Classical.BasicProperties

namespace Complexity.Classical.Certificates
open PolynomialTime
example : ∀ (x y : Word),
    unpair (pair x y) = some (x, y) :=
  @Complexity.Classical.Certificates.unpair_pair
end Complexity.Classical.Certificates

namespace Complexity.Classical.Certificates
open PolynomialTime
example : Function.Injective (fun p : Word × Word => pair p.1 p.2) :=
  @Complexity.Classical.Certificates.pair_injective
end Complexity.Classical.Certificates

namespace Complexity.Classical.Certificates
open PolynomialTime
example : ∀ (x y : Word),
    (pair x y).length = 2 * x.length + y.length + 1 :=
  @Complexity.Classical.Certificates.pair_length
end Complexity.Classical.Certificates

namespace Complexity.Classical.ComplementClosure
open Complexity.Classical.PolynomialTime
example : ∀ (L : Language),
    L ∈ P → Lᶜ ∈ P :=
  @Complexity.Classical.ComplementClosure.closed_under_complement
end Complexity.Classical.ComplementClosure

namespace Complexity.Classical.FiniteStackEquivalence
open PolynomialTime MachineModels
example : FiniteStackP = P :=
  @Complexity.Classical.FiniteStackEquivalence.finiteStackP_eq_P
end Complexity.Classical.FiniteStackEquivalence

namespace Complexity.Classical.ModelEquivalence
open PolynomialTime MachineModels
example : SingleTapeP = P :=
  @Complexity.Classical.ModelEquivalence.singleTapeP_eq_P
end Complexity.Classical.ModelEquivalence

namespace Complexity.Classical.PolynomialSpaceEquality
open PolynomialSpace NondeterministicPolynomialSpace
example : PSPACE = NPSPACE :=
  @Complexity.Classical.PolynomialSpaceEquality.PSPACE_eq_NPSPACE
end Complexity.Classical.PolynomialSpaceEquality

namespace Complexity.Classical.SingleTapeComplement
open PolynomialTime MachineModels
example : ∀ (L : Language),
    L ∈ SingleTapeP → Lᶜ ∈ SingleTapeP :=
  @Complexity.Classical.SingleTapeComplement.closed_under_complement
end Complexity.Classical.SingleTapeComplement

namespace Complexity.CookLevin.CircuitMachine
open Complexity.Classical.PolynomialTime Complexity.Classical.Certificates Circuits Encoding
example : ∀ (V : Language) (hV : V ∈ P) (p : Polynomial ℕ),
    ∃ circuits : Word → Circuit, Nonempty (Turing.TM2ComputableInPolyTime id id (fun x => encodeCNF (Tseitin.encode (circuits x)))) ∧ ∀ x, Satisfiable (circuits x) ↔ ∃ y : Word, y.length ≤ p.eval x.length ∧ pair x y ∈ V :=
  @Complexity.CookLevin.CircuitMachine.compile
end Complexity.CookLevin.CircuitMachine

namespace Complexity.CookLevin.CookLevin
open Satisfiability Reductions
example : NPComplete SAT :=
  @Complexity.CookLevin.CookLevin.np_complete
end Complexity.CookLevin.CookLevin

namespace Complexity.CookLevin.EncodingCorrect
open CNF Encoding
example : ∀ (F : Formula),
    decodeCNF (encodeCNF F) = some F :=
  @Complexity.CookLevin.EncodingCorrect.roundtrip
end Complexity.CookLevin.EncodingCorrect

namespace Complexity.CookLevin.FiniteWitness
open CNF Encoding Satisfiability Complexity.Classical.PolynomialTime
example : ∀ (F : Formula),
    Satisfiable F ↔ ∃ y : Word, y.length ≤ (encodeCNF F).length ∧ eval F (assignment y) = true :=
  @Complexity.CookLevin.FiniteWitness.bounded
end Complexity.CookLevin.FiniteWitness

namespace Complexity.CookLevin.GateCorrect
open CNF Circuits Tseitin
example : ∀ (i : ℕ) (g : Gate) (ρ : Assignment),
    eval (gateClauses i g) ρ = g.check ρ i :=
  @Complexity.CookLevin.GateCorrect.correct
end Complexity.CookLevin.GateCorrect

namespace Complexity.CookLevin.SATEncoding
open CNF Encoding Satisfiability
example : ∀ (F : Formula),
    encodeCNF F ∈ SAT ↔ Satisfiable F :=
  @Complexity.CookLevin.SATEncoding.correct
end Complexity.CookLevin.SATEncoding

namespace Complexity.CookLevin.SATHard
open Satisfiability Reductions Complexity.Classical.PolynomialTime Complexity.Classical.NondeterministicPolynomialTime
example : ∀ (A : Language),
    A ∈ NP → ManyOne A SAT :=
  @Complexity.CookLevin.SATHard.hardness
end Complexity.CookLevin.SATHard

namespace Complexity.CookLevin.SATinNP
open Satisfiability Complexity.Classical.NondeterministicPolynomialTime
example : SAT ∈ NP :=
  @Complexity.CookLevin.SATinNP.membership
end Complexity.CookLevin.SATinNP

namespace Complexity.CookLevin.TseitinCorrect
open Circuits
example : ∀ (C : Circuit),
    CNF.Satisfiable (Tseitin.encode C) ↔ Satisfiable C :=
  @Complexity.CookLevin.TseitinCorrect.correct
end Complexity.CookLevin.TseitinCorrect

namespace Complexity.CookLevin.VerifierCorrect
open Satisfiability Complexity.Classical.PolynomialTime Complexity.Classical.Certificates
example : ∀ (w : Word),
    w ∈ SAT ↔ ∃ y : Word, y.length ≤ w.length ∧ pair w y ∈ Verifier :=
  @Complexity.CookLevin.VerifierCorrect.correct
end Complexity.CookLevin.VerifierCorrect

namespace Complexity.CookLevin.VerifierTime
open Satisfiability Complexity.Classical.PolynomialTime
example : Verifier ∈ P :=
  @Complexity.CookLevin.VerifierTime.polynomial
end Complexity.CookLevin.VerifierTime

namespace Complexity.ArcKayles.Biclique
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S L R I : Finset V) (h : Partition G S L R I),
    Grundy.value G S = g L.card R.card :=
  @Complexity.ArcKayles.Biclique.value_eq
end Complexity.ArcKayles.Biclique

namespace Complexity.ArcKayles.Completeness
example : Encoding.arcKayles ∈ Complexity.Classical.PolynomialSpace.PSPACE :=
  @Complexity.ArcKayles.Completeness.membership
end Complexity.ArcKayles.Completeness

namespace Complexity.ArcKayles.Completeness
example : PSPACE.Complete Encoding.arcKayles :=
  @Complexity.ArcKayles.Completeness.pspace_complete
end Complexity.ArcKayles.Completeness

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (i : ℕ) (h : i < value G S),
    ∃ u ∈ S, ∃ v ∈ S, G.Adj u v ∧ value G (remove S u v) = i :=
  @Complexity.ArcKayles.GrundyProperties.smaller_reachable
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (u v : V) (hu : u ∈ S) (hv : v ∈ S) (he : G.Adj u v),
    value G (remove S u v) ≠ value G S :=
  @Complexity.ArcKayles.GrundyProperties.value_not_reachable
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S : Finset V),
    ¬ Winning G S ↔ value G S = 0 :=
  @Complexity.ArcKayles.GrundyProperties.losing_iff_zero
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S T : Finset V) (hd : Disjoint S T) (hn : ∀ u ∈ S, ∀ v ∈ T, ¬ G.Adj u v),
    value G (S ∪ T) = Nat.xor (value G S) (value G T) :=
  @Complexity.ArcKayles.GrundyProperties.disjoint_union
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.Passes
open PositiveCNF
example : ∀ (φ : Formula) (U T : Finset (Fin φ.nvars)) (hd : Disjoint U T) (turn : Bool) (passes : ℕ),
    TrueWins φ U T turn passes ↔ PositiveCNF.TrueWins φ U T turn :=
  @Complexity.ArcKayles.Passes.outcome_equivalent
end Complexity.ArcKayles.Passes

namespace Complexity.ArcKayles.PositiveCNFHardness
example : PSPACE.Hard Encoding.positiveCNF :=
  @Complexity.ArcKayles.PositiveCNFHardness.hard
end Complexity.ArcKayles.PositiveCNFHardness

namespace Complexity.ArcKayles.Reduction
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (h : ¬ FirstWins φ),
    ¬ Winning (graph φ) (board φ) :=
  @Complexity.ArcKayles.Reduction.false_strategy
end Complexity.ArcKayles.Reduction

namespace Complexity.ArcKayles.Reduction
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (h : FirstWins φ),
    Winning (graph φ) (board φ) :=
  @Complexity.ArcKayles.Reduction.true_strategy
end Complexity.ArcKayles.Reduction

namespace Complexity.ArcKayles.Reduction
open PositiveCNF Construction ArcKayles
example : Complexity.CookLevin.Reductions.ManyOne Encoding.positiveCNF Encoding.arcKayles :=
  @Complexity.ArcKayles.Reduction.polynomial_reduction
end Complexity.ArcKayles.Reduction

namespace Complexity.ArcKayles.RegularPlay
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (S : Finset ℕ) (hS : Reachable φ S) (hr : φ.clauses.length ≤ remainingV φ S) (hk : 1 ≤ remainingY φ S) (u w : ℕ) (hu : u ∈ S) (hw : w ∈ S) (he : (graph φ).Adj u w) (hn : ¬ RegularMove φ u w) (hx : ¬ Exceptional φ S u w),
    Winning (graph φ) (remove S u w) :=
  @Complexity.ArcKayles.RegularPlay.deviation_loses
end Complexity.ArcKayles.RegularPlay

namespace Complexity.ArcKayles.RegularPlay
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (S : Finset ℕ) (hS : Reachable φ S) (hr : φ.clauses.length ≤ remainingV φ S) (j : Fin φ.clauses.length) (hj : Exhausted φ S j),
    ¬ Winning (graph φ) (remove S s (a φ j)) ↔ (remainingV φ S + remainingY φ S) % 2 = 0 :=
  @Complexity.ArcKayles.RegularPlay.exceptional_parity
end Complexity.ArcKayles.RegularPlay

namespace Complexity.ArcKayles.Sizes
example : ∀ (G : Encoding.Graph),
    (Encoding.graphWord G).length = G.vertices ^ 2 + G.vertices + 1 :=
  @Complexity.ArcKayles.Sizes.graph_length
end Complexity.ArcKayles.Sizes

namespace Complexity.ArcKayles.Sizes
example : ∀ (φ : PositiveCNF.Formula),
    (Encoding.formulaWord φ).length = φ.clauses.length * φ.nvars + φ.nvars + φ.clauses.length + 2 :=
  @Complexity.ArcKayles.Sizes.formula_length
end Complexity.ArcKayles.Sizes

namespace Complexity.ArcKayles.Sizes
example : ∀ (φ : PositiveCNF.Formula),
    Construction.size φ = 13 * φ.nvars + 4 * φ.clauses.length + 18 :=
  @Complexity.ArcKayles.Sizes.construction_size
end Complexity.ArcKayles.Sizes
