/-
Generated by the port script: every removed concept axiom is restated verbatim
here (binders and statement copied from the archived concept file) and checked against
the theorem that now carries its name. If a ported proof ever proved a different
statement than the archived concept, this file fails to build.
-/
import Complexity

namespace Complexity.Classes.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : L ⊆ NL :=
  @Complexity.Classes.BasicProperties.L_subset_NL
end Complexity.Classes.BasicProperties

namespace Complexity.Classes.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : NL ⊆ P :=
  @Complexity.Classes.BasicProperties.NL_subset_P
end Complexity.Classes.BasicProperties

namespace Complexity.Classes.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : P ⊆ NP :=
  @Complexity.Classes.BasicProperties.P_subset_NP
end Complexity.Classes.BasicProperties

namespace Complexity.Classes.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : NP ⊆ PSPACE :=
  @Complexity.Classes.BasicProperties.NP_subset_PSPACE
end Complexity.Classes.BasicProperties

namespace Complexity.Classes.BasicProperties
open PolynomialTime LogarithmicSpace NondeterministicLogarithmicSpace
open NondeterministicPolynomialTime PolynomialSpace NondeterministicPolynomialSpace
open ExponentialTime
example : NPSPACE ⊆ EXPTIME :=
  @Complexity.Classes.BasicProperties.NPSPACE_subset_EXPTIME
end Complexity.Classes.BasicProperties

namespace Complexity.Classes.Certificates
open PolynomialTime
example : ∀ (x y : Word),
    unpair (pair x y) = some (x, y) :=
  @Complexity.Classes.Certificates.unpair_pair
end Complexity.Classes.Certificates

namespace Complexity.Classes.Certificates
open PolynomialTime
example : Function.Injective (fun p : Word × Word => pair p.1 p.2) :=
  @Complexity.Classes.Certificates.pair_injective
end Complexity.Classes.Certificates

namespace Complexity.Classes.Certificates
open PolynomialTime
example : ∀ (x y : Word),
    (pair x y).length = 2 * x.length + y.length + 1 :=
  @Complexity.Classes.Certificates.pair_length
end Complexity.Classes.Certificates

namespace Complexity.Classes.ComplementClosure
open Complexity.Classes.PolynomialTime
example : ∀ (L : Language),
    L ∈ P → Lᶜ ∈ P :=
  @Complexity.Classes.ComplementClosure.closed_under_complement
end Complexity.Classes.ComplementClosure

namespace Complexity.Classes.FiniteStackEquivalence
open PolynomialTime MachineModels
example : FiniteStackP = P :=
  @Complexity.Classes.FiniteStackEquivalence.finiteStackP_eq_P
end Complexity.Classes.FiniteStackEquivalence

namespace Complexity.Classes.ModelEquivalence
open PolynomialTime MachineModels
example : SingleTapeP = P :=
  @Complexity.Classes.ModelEquivalence.singleTapeP_eq_P
end Complexity.Classes.ModelEquivalence

namespace Complexity.Classes.PolynomialSpaceEquality
open PolynomialSpace NondeterministicPolynomialSpace
example : PSPACE = NPSPACE :=
  @Complexity.Classes.PolynomialSpaceEquality.PSPACE_eq_NPSPACE
end Complexity.Classes.PolynomialSpaceEquality

namespace Complexity.Classes.SingleTapeComplement
open PolynomialTime MachineModels
example : ∀ (L : Language),
    L ∈ SingleTapeP → Lᶜ ∈ SingleTapeP :=
  @Complexity.Classes.SingleTapeComplement.closed_under_complement
end Complexity.Classes.SingleTapeComplement

namespace Complexity.CookLevin.CircuitMachine
open Complexity.Classes.PolynomialTime Complexity.Classes.Certificates Circuits Encoding
example : ∀ (V : Language) (hV : V ∈ P) (p : Polynomial ℕ),
    ∃ circuits : Word → Circuit, Nonempty (Turing.TM2ComputableInPolyTime id id (fun x => encodeCNF (Tseitin.encode (circuits x)))) ∧ ∀ x, Satisfiable (circuits x) ↔ ∃ y : Word, y.length ≤ p.eval x.length ∧ pair x y ∈ V :=
  @Complexity.CookLevin.CircuitMachine.compile
end Complexity.CookLevin.CircuitMachine

namespace Complexity.CookLevin.CookLevin
open Satisfiability Reductions
example : NPComplete SAT :=
  @Complexity.CookLevin.CookLevin.np_complete
end Complexity.CookLevin.CookLevin

namespace Complexity.CookLevin.EncodingCorrect
open CNF Encoding
example : ∀ (F : Formula),
    decodeCNF (encodeCNF F) = some F :=
  @Complexity.CookLevin.EncodingCorrect.roundtrip
end Complexity.CookLevin.EncodingCorrect

namespace Complexity.CookLevin.FiniteWitness
open CNF Encoding Satisfiability Complexity.Classes.PolynomialTime
example : ∀ (F : Formula),
    Satisfiable F ↔ ∃ y : Word, y.length ≤ (encodeCNF F).length ∧ eval F (assignment y) = true :=
  @Complexity.CookLevin.FiniteWitness.bounded
end Complexity.CookLevin.FiniteWitness

namespace Complexity.CookLevin.GateCorrect
open CNF Circuits Tseitin
example : ∀ (i : ℕ) (g : Gate) (ρ : Assignment),
    eval (gateClauses i g) ρ = g.check ρ i :=
  @Complexity.CookLevin.GateCorrect.correct
end Complexity.CookLevin.GateCorrect

namespace Complexity.CookLevin.SATEncoding
open CNF Encoding Satisfiability
example : ∀ (F : Formula),
    encodeCNF F ∈ SAT ↔ Satisfiable F :=
  @Complexity.CookLevin.SATEncoding.correct
end Complexity.CookLevin.SATEncoding

namespace Complexity.CookLevin.SATHard
open Satisfiability Reductions Complexity.Classes.PolynomialTime Complexity.Classes.NondeterministicPolynomialTime
example : ∀ (A : Language),
    A ∈ NP → ManyOne A SAT :=
  @Complexity.CookLevin.SATHard.hardness
end Complexity.CookLevin.SATHard

namespace Complexity.CookLevin.SATinNP
open Satisfiability Complexity.Classes.NondeterministicPolynomialTime
example : SAT ∈ NP :=
  @Complexity.CookLevin.SATinNP.membership
end Complexity.CookLevin.SATinNP

namespace Complexity.CookLevin.TseitinCorrect
open Circuits
example : ∀ (C : Circuit),
    CNF.Satisfiable (Tseitin.encode C) ↔ Satisfiable C :=
  @Complexity.CookLevin.TseitinCorrect.correct
end Complexity.CookLevin.TseitinCorrect

namespace Complexity.CookLevin.VerifierCorrect
open Satisfiability Complexity.Classes.PolynomialTime Complexity.Classes.Certificates
example : ∀ (w : Word),
    w ∈ SAT ↔ ∃ y : Word, y.length ≤ w.length ∧ pair w y ∈ Verifier :=
  @Complexity.CookLevin.VerifierCorrect.correct
end Complexity.CookLevin.VerifierCorrect

namespace Complexity.CookLevin.VerifierTime
open Satisfiability Complexity.Classes.PolynomialTime
example : Verifier ∈ P :=
  @Complexity.CookLevin.VerifierTime.polynomial
end Complexity.CookLevin.VerifierTime

namespace Complexity.ArcKayles.Biclique
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S L R I : Finset V) (h : Partition G S L R I),
    Grundy.value G S = g L.card R.card :=
  @Complexity.ArcKayles.Biclique.value_eq
end Complexity.ArcKayles.Biclique

namespace Complexity.ArcKayles.Completeness
example : Encoding.arcKayles ∈ Complexity.Classes.PolynomialSpace.PSPACE :=
  @Complexity.ArcKayles.Completeness.membership
end Complexity.ArcKayles.Completeness

namespace Complexity.ArcKayles.Completeness
example : PSPACE.Complete Encoding.arcKayles :=
  @Complexity.ArcKayles.Completeness.pspace_complete
end Complexity.ArcKayles.Completeness

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (i : ℕ) (h : i < value G S),
    ∃ u ∈ S, ∃ v ∈ S, G.Adj u v ∧ value G (remove S u v) = i :=
  @Complexity.ArcKayles.GrundyProperties.smaller_reachable
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S : Finset V) (u v : V) (hu : u ∈ S) (hv : v ∈ S) (he : G.Adj u v),
    value G (remove S u v) ≠ value G S :=
  @Complexity.ArcKayles.GrundyProperties.value_not_reachable
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S : Finset V),
    ¬ Winning G S ↔ value G S = 0 :=
  @Complexity.ArcKayles.GrundyProperties.losing_iff_zero
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.GrundyProperties
open ArcKayles Grundy
example : ∀ {V : Type} [DecidableEq V] (G : SimpleGraph V) (S T : Finset V) (hd : Disjoint S T) (hn : ∀ u ∈ S, ∀ v ∈ T, ¬ G.Adj u v),
    value G (S ∪ T) = Nat.xor (value G S) (value G T) :=
  @Complexity.ArcKayles.GrundyProperties.disjoint_union
end Complexity.ArcKayles.GrundyProperties

namespace Complexity.ArcKayles.Passes
open PositiveCNF
example : ∀ (φ : Formula) (U T : Finset (Fin φ.nvars)) (hd : Disjoint U T) (turn : Bool) (passes : ℕ),
    TrueWins φ U T turn passes ↔ PositiveCNF.TrueWins φ U T turn :=
  @Complexity.ArcKayles.Passes.outcome_equivalent
end Complexity.ArcKayles.Passes

namespace Complexity.ArcKayles.PositiveCNFHardness
example : PSPACE.Hard Encoding.positiveCNF :=
  @Complexity.ArcKayles.PositiveCNFHardness.hard
end Complexity.ArcKayles.PositiveCNFHardness

namespace Complexity.ArcKayles.Reduction
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (h : ¬ FirstWins φ),
    ¬ Winning (graph φ) (board φ) :=
  @Complexity.ArcKayles.Reduction.false_strategy
end Complexity.ArcKayles.Reduction

namespace Complexity.ArcKayles.Reduction
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (h : FirstWins φ),
    Winning (graph φ) (board φ) :=
  @Complexity.ArcKayles.Reduction.true_strategy
end Complexity.ArcKayles.Reduction

namespace Complexity.ArcKayles.Reduction
open PositiveCNF Construction ArcKayles
example : Complexity.CookLevin.Reductions.ManyOne Encoding.positiveCNF Encoding.arcKayles :=
  @Complexity.ArcKayles.Reduction.polynomial_reduction
end Complexity.ArcKayles.Reduction

namespace Complexity.ArcKayles.RegularPlay
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (S : Finset ℕ) (hS : Reachable φ S) (hr : φ.clauses.length ≤ remainingV φ S) (hk : 1 ≤ remainingY φ S) (u w : ℕ) (hu : u ∈ S) (hw : w ∈ S) (he : (graph φ).Adj u w) (hn : ¬ RegularMove φ u w) (hx : ¬ Exceptional φ S u w),
    Winning (graph φ) (remove S u w) :=
  @Complexity.ArcKayles.RegularPlay.deviation_loses
end Complexity.ArcKayles.RegularPlay

namespace Complexity.ArcKayles.RegularPlay
open PositiveCNF Construction ArcKayles
example : ∀ (φ : Formula) (hm : φ.clauses.length % 2 = 1) (S : Finset ℕ) (hS : Reachable φ S) (hr : φ.clauses.length ≤ remainingV φ S) (j : Fin φ.clauses.length) (hj : Exhausted φ S j),
    ¬ Winning (graph φ) (remove S s (a φ j)) ↔ (remainingV φ S + remainingY φ S) % 2 = 0 :=
  @Complexity.ArcKayles.RegularPlay.exceptional_parity
end Complexity.ArcKayles.RegularPlay

namespace Complexity.ArcKayles.Sizes
example : ∀ (G : Encoding.Graph),
    (Encoding.graphWord G).length = G.vertices ^ 2 + G.vertices + 1 :=
  @Complexity.ArcKayles.Sizes.graph_length
end Complexity.ArcKayles.Sizes

namespace Complexity.ArcKayles.Sizes
example : ∀ (φ : PositiveCNF.Formula),
    (Encoding.formulaWord φ).length = φ.clauses.length * φ.nvars + φ.nvars + φ.clauses.length + 2 :=
  @Complexity.ArcKayles.Sizes.formula_length
end Complexity.ArcKayles.Sizes

namespace Complexity.ArcKayles.Sizes
example : ∀ (φ : PositiveCNF.Formula),
    Construction.size φ = 13 * φ.nvars + 4 * φ.clauses.length + 18 :=
  @Complexity.ArcKayles.Sizes.construction_size
end Complexity.ArcKayles.Sizes

/-! ## Milestone 2 statements

Textbook restatements of the new theorems, checked against the declarations that carry them. -/

section Milestone2
open Complexity.Classes.PolynomialTime Complexity.Classes.PolynomialSpace
open Complexity.Classes.NondeterministicPolynomialSpace

/-- Savitch's theorem, inclusion form. -/
example : NPSPACE ⊆ PSPACE := Complexity.Savitch.NPSPACE_subset_PSPACE
example : PSPACE = NPSPACE := Complexity.Savitch.PSPACE_eq_NPSPACE

/-- The game template: every polynomially bounded normal-play game with computable moves has
its winner-determination language in PSPACE. -/
example : ∀ G : Complexity.Games.Game, G.language ∈ PSPACE :=
  Complexity.Games.Game.language_mem_PSPACE

/-- Normal-play recursion of the template's winning positions. -/
example : ∀ (G : Complexity.Games.Game) (w p : Word), G.Bounded w p →
    (G.Winning w p ↔ ∃ q, G.Move w p q ∧ ¬ G.Winning w q) :=
  fun G w p hp => G.winning_iff hp

/-- Every closed QBF has a word, and every valid word is the word of a closed QBF. -/
example : ∀ φ : Complexity.QBF.Formula, φ.Closed → Complexity.QBF.decode (Complexity.QBF.encode φ) = some φ :=
  Complexity.QBF.decode_encode
example : ∀ (w : Word) (φ : Complexity.QBF.Formula), Complexity.QBF.decode w = some φ → φ.Closed :=
  fun _ _ h => Complexity.QBF.decode_closed h

/-- TQBF is the set of words decoding to a true QBF, and it is the language of the formula game. -/
example : Complexity.QBF.TQBF = {w | ∃ φ : Complexity.QBF.Formula, Complexity.QBF.decode w = some φ ∧ φ.IsTrue} :=
  rfl
example : Complexity.QBF.TQBFGame.game.language = Complexity.QBF.TQBF :=
  Complexity.QBF.TQBFGame.language_eq

/-- TQBF is in PSPACE, PSPACE-hard under polynomial-time many-one reductions, hence complete. -/
example : Complexity.QBF.TQBF ∈ PSPACE := Complexity.QBF.TQBF_mem_PSPACE
example : ∀ A : Language, A ∈ PSPACE → Complexity.CookLevin.Reductions.ManyOne A Complexity.QBF.TQBF :=
  Complexity.QBF.TQBF_hard
example : Complexity.QBF.TQBF ∈ PSPACE ∧
    ∀ A : Language, A ∈ PSPACE → Complexity.CookLevin.Reductions.ManyOne A Complexity.QBF.TQBF :=
  Complexity.QBF.TQBF_complete

end Milestone2

/-! ## Milestone 3 statements

The modular `j`-function and its `q`-expansion, restated in textbook form. -/

section Milestone3
open UpperHalfPlane ModularForm MatrixGroups Complexity.Modular

/-- `j = E₄³ / Δ` with Mathlib's `Δ = η²⁴ = q ∏ (1 − qⁿ)²⁴`; the defining equation. -/
example : ∀ z : ℍ, j z * ModularForm.discriminant z = E₄ z ^ 3 := j_mul_discriminant

/-- The defining equation with the discriminant normalised as `E₄³ − E₆² (= 1728 Δ)`. -/
example : ∀ z : ℍ, j z * (E₄ z ^ 3 - E₆ z ^ 2) = 1728 * E₄ z ^ 3 := j_mul_E₄_cube_sub_E₆_sq
example : ∀ z : ℍ, j z = 1728 * E₄ z ^ 3 / (E₄ z ^ 3 - E₆ z ^ 2) := j_eq_E₄_cube_sub_E₆_sq

/-- Invariance under the full modular group. -/
example : ∀ (γ : SL(2, ℤ)) (z : ℍ), j (γ • z) = j z := j_SL_smul
example : ∀ γ : SL(2, ℤ), j ∣[(0 : ℤ)] γ = j := j_slash_invariant

/-- Stage (a): `q · j` extends holomorphically to the open unit disc with value `1` at `q = 0`. -/
example : cuspFunction 1 qj 0 = 1 := cuspFunction_qj_zero
example : DifferentiableOn ℂ (cuspFunction 1 qj) (Metric.ball 0 1) := differentiableOn_cuspFunction_qj
example : (qExpansion 1 qj).coeff 0 = 1 := qExpansion_qj_coeff_zero

/-- The Laurent expansion `j τ = q⁻¹ Σ Q_m qᵐ` converges for every `τ ∈ ℍ`. -/
example : ∀ τ : ℍ,
    HasSum (fun m ↦ (qExpansion 1 qj).coeff m * Function.Periodic.qParam 1 τ ^ m) (Function.Periodic.qParam 1 τ * j τ) :=
  hasSum_qExpansion_qj

/-- Stage (b): the constant term of `j` is `744`. -/
example : (qExpansion 1 qj).coeff 1 = 744 := qExpansion_qj_coeff_one

/-- Stage (c): the coefficient of `q` in `j` is `196884`. -/
example : (qExpansion 1 qj).coeff 2 = 196884 := qExpansion_qj_coeff_two

end Milestone3
